// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAX2l2F1t28u66_ghHChagnUUb9f7k0g3Y',
    appId: '1:688864274129:web:74539b4ac105e2e7d947f0',
    messagingSenderId: '688864274129',
    projectId: 'pets-5e267',
    authDomain: 'pets-5e267.firebaseapp.com',
    databaseURL: 'https://pets-5e267-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'pets-5e267.appspot.com',
    measurementId: 'G-QQRZ6C45J9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAllPSuxCuUYs_URRMS9Dd5b-AqkJ-7_OU',
    appId: '1:688864274129:android:7b751632dfa3c7bbd947f0',
    messagingSenderId: '688864274129',
    projectId: 'pets-5e267',
    databaseURL: 'https://pets-5e267-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'pets-5e267.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpOSvUL9O5kYw_nMeGa8NC6oCtQjIeD8U',
    appId: '1:688864274129:ios:0d305f684c517969d947f0',
    messagingSenderId: '688864274129',
    projectId: 'pets-5e267',
    databaseURL: 'https://pets-5e267-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'pets-5e267.appspot.com',
    androidClientId: '688864274129-ulo2kqh6npomot9gq98mcgitjmadffts.apps.googleusercontent.com',
    iosClientId: '688864274129-9l7q0c43shv9ginupchdbd8ab237adug.apps.googleusercontent.com',
    iosBundleId: 'com.example.pets',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpOSvUL9O5kYw_nMeGa8NC6oCtQjIeD8U',
    appId: '1:688864274129:ios:0d305f684c517969d947f0',
    messagingSenderId: '688864274129',
    projectId: 'pets-5e267',
    databaseURL: 'https://pets-5e267-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'pets-5e267.appspot.com',
    androidClientId: '688864274129-ulo2kqh6npomot9gq98mcgitjmadffts.apps.googleusercontent.com',
    iosClientId: '688864274129-9l7q0c43shv9ginupchdbd8ab237adug.apps.googleusercontent.com',
    iosBundleId: 'com.example.pets',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAX2l2F1t28u66_ghHChagnUUb9f7k0g3Y',
    appId: '1:688864274129:web:5203a2c8383d2345d947f0',
    messagingSenderId: '688864274129',
    projectId: 'pets-5e267',
    authDomain: 'pets-5e267.firebaseapp.com',
    databaseURL: 'https://pets-5e267-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'pets-5e267.appspot.com',
    measurementId: 'G-HX2XS8J8D9',
  );

}